// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_batVoltage;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_iplbl;
extern lv_obj_t * ui_gatewaylbl;
extern lv_obj_t * ui_subnetlbl;
extern lv_obj_t * ui_maclbl;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_statusLBL;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_885539969);    // assets\Wifi-1-icon.png
LV_IMG_DECLARE(ui_img_1537598557);    // assets\Dakirby309-Simply-Styled-YouTube.24.png
LV_IMG_DECLARE(ui_img_923627907);    // assets\Steve-Zondicons-Usb.72.png
LV_IMG_DECLARE(ui_img_1143977843);    // assets\Steve-Zondicons-Usb.96.png

LV_FONT_DECLARE(ui_font_big);
LV_FONT_DECLARE(ui_font_m2);
LV_FONT_DECLARE(ui_font_mid);
LV_FONT_DECLARE(ui_font_small);
LV_FONT_DECLARE(ui_font_MINI);
LV_FONT_DECLARE(ui_font_M3);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
