// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x030F16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 78);
    lv_obj_set_height(ui_Panel1, 78);
    lv_obj_set_x(ui_Panel1, -209);
    lv_obj_set_y(ui_Panel1, -78);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Panel1, &ui_img_885539969, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Panel1, lv_color_hex(0x886C0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batVoltage = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_batVoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batVoltage, 24);
    lv_obj_set_y(ui_batVoltage, 143);
    lv_label_set_text(ui_batVoltage, "-50");
    lv_obj_set_style_text_color(ui_batVoltage, lv_color_hex(0xB5CADF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_batVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_batVoltage, &ui_font_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -214);
    lv_obj_set_y(ui_Label2, -12);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "RSSI");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x4C6B8A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_mid, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -125);
    lv_obj_set_y(ui_Label3, 97);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "dBm");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x526880), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -80);
    lv_obj_set_y(ui_Label4, -76);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "WiFi TEST");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xA0BAD3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_m2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -110);
    lv_obj_set_y(ui_Label6, -12);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Received Signal \nStrength Indicator");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x484D30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_MINI, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 69);
    lv_obj_set_y(ui_Label12, 13);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "MAC:\nIP:\nGATEWAY:\nSUBNET:");
    lv_label_set_recolor(ui_Label12, "true");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x305274), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iplbl = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_iplbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iplbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iplbl, 386);
    lv_obj_set_y(ui_iplbl, 102);
    lv_label_set_text(ui_iplbl, "192.168.2.1");
    lv_obj_set_style_text_color(ui_iplbl, lv_color_hex(0x92A8C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_iplbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iplbl, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gatewaylbl = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_gatewaylbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gatewaylbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gatewaylbl, 387);
    lv_obj_set_y(ui_gatewaylbl, 132);
    lv_label_set_text(ui_gatewaylbl, "192");
    lv_obj_set_style_text_color(ui_gatewaylbl, lv_color_hex(0x92A8C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gatewaylbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gatewaylbl, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_subnetlbl = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_subnetlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_subnetlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_subnetlbl, 387);
    lv_obj_set_y(ui_subnetlbl, 162);
    lv_label_set_text(ui_subnetlbl, "192");
    lv_obj_set_style_text_color(ui_subnetlbl, lv_color_hex(0x92A8C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_subnetlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_subnetlbl, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_maclbl = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_maclbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_maclbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_maclbl, 386);
    lv_obj_set_y(ui_maclbl, 72);
    lv_label_set_text(ui_maclbl, "192");
    lv_obj_set_style_text_color(ui_maclbl, lv_color_hex(0x92A8C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_maclbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_maclbl, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 2);
    lv_obj_set_height(ui_Panel3, 175);
    lv_obj_set_x(ui_Panel3, 19);
    lv_obj_set_y(ui_Panel3, 19);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x8095BC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusLBL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_statusLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statusLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_statusLBL, 340);
    lv_obj_set_y(ui_statusLBL, 10);
    lv_label_set_text(ui_statusLBL, "DISCONECTED");
    lv_obj_set_style_text_color(ui_statusLBL, lv_color_hex(0x484D30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_statusLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_statusLBL, &ui_font_M3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 40);
    lv_obj_set_y(ui_Label9, -93);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "STATUS:");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x856A08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_MINI, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -12);
    lv_obj_set_y(ui_Label10, 38);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "BEST\nGOOD\nFAIR\nWEAK\nPOOR\nBAD");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x68819A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_MINI, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 171);
    lv_obj_set_y(ui_Label5, 102);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "VolosProjects 2025");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x183849), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 6);
    lv_obj_set_height(ui_Panel4, 23);
    lv_obj_set_x(ui_Panel4, -36);
    lv_obj_set_y(ui_Panel4, -23);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xD52020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -106);
    lv_obj_set_y(ui_Label11, 47);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "AVERAGE:\nMAX:\nMIN:");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x43566A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_1537598557);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image1, 245);
    lv_obj_set_y(ui_Image1, 102);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 166);
    lv_obj_set_y(ui_Label1, 86);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "I will rule this Galaxy!");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x142D3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

}
